#flink
#job manager
jobmanager.rpc.address: jobmanager
jobmanager.rpc.port: 6123
jobmanager.heap.size: 1024m

#task manager
taskmanager.heap.size: 1024m
taskmanager.numberOfTaskSlots: 2

#general
parallelism.default: 2
state.backend: filesystem
state.checkpoints.dir: file:///tmp/flink-checkpoints
state.savepoints.dir: file:///tmp/flink-savepoints

#ui j'ai le port changÃ© car 8081 deja pris
rest.port: 8082
# kafka
bootstrap.servers: broker:9092
schema.registery.url: http://schema-registry:8081