blob:
  server:
    port: '6124'
topic:
  member:
    out:
      deleted: training_bench_connect.public.members-deleted
      changed: training_bench_connect.public.members-changed
      created: training_bench_connect_public_members-created
    in: training_bench_connect.public.members
jobmanager:
  execution:
    failover-strategy: region
  rpc:
    address: jobmanager
    port: 6123
  bind-host: 0.0.0.0
  memory:
    process:
      size: 1600m
group:
  id: training-bench-consumer
bootstrap:
  servers: broker:29092
query:
  server:
    port: '6125'
schema:
  registry:
    url: http://schema-registry:8081
parallelism:
  default: 1
taskmanager:
  numberOfTaskSlots: '2'
  memory:
    process:
      size: 1728m
  bind-host: 0.0.0.0
env:
  java:
    opts:
      all: --add-exports=java.base/sun.net.util=ALL-UNNAMED --add-exports=java.rmi/sun.rmi.registry=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED --add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.base/java.time=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.locks=ALL-UNNAMED
subject:
  created:
    value: training_bench_connect.public.members.Envelope
    key: training_bench_connect.public.members.Key
  changed: training_bench_connect.public.members-changed-value
  deleted: training_bench_connect.public.members-deleted-value
rest:
  bind-address: 0.0.0.0
  address: 0.0.0.0
