services:
  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
  kafka-ui0:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui0
    depends_on:
      - broker
    ports:
      - "8080:8080"

    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: bangbang
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:29092
  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.0
    container_name: schema-registry
    hostname: schema-registry
    platform: linux/amd64
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:29092'
      SCHEMA_REGISTRY_LISTENERS: 'http://schema-registry:8081'
    depends_on:
      - broker

  postgres:
    image: debezium/postgres:13
    ports:
        - 5432:5432
    environment:
      - POSTGRES_USER=saza
      - POSTGRES_PASSWORD=mizer
      - POSTGRES_DB=traingbench
 
  dbz:
    image: quay.io/debezium/connect:3.2
    container_name: dbz
    depends_on:
      - broker
      - schema-registry
    ports:
      - 8083:8083
      - 9012:9012
    environment:
      BOOTSTRAP_SERVERS: broker:29092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: training_bench_connect_connect_configs
      OFFSET_STORAGE_TOPIC: training_bench_connect_connect_offsets
      STATUS_STORAGE_TOPIC: training_bench_connect_connect_statuses
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: debezium
      CONNECT_PLUGIN_PATH: /kafka/connect/
      

    volumes:
      - ./confluentinc-kafka-connect-avro-converter/lib:/kafka/connect/libs
  jobmanager:
    image: flink:latest
    ports:
      - "8082:8081"
    command: jobmanager
    volumes: 
      - ./training-bench-flink/training-bench-flink/config/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager        

  taskmanager:
    image: flink:latest
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1    
    volumes: 
      - ./training-bench-flink/training-bench-flink/config/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2          
    
